name: botonera_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.8.0
  flutter_launcher_icons: ^0.7.4
  path_provider: ^0.5.0
  cupertino_icons: ^1.0.0
  sqflite:
  esys_flutter_share: ^1.0.1
  flutter_colorpicker: ^0.3.5
  color_parser: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: 'assets/icon/logo.png'
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audios/